name: 'Terraform Module Testing - Linux Shells'
description: 'Tests the Terraform module on various Linux shells.'

inputs:
  terraform_version:
    description: "The version of Terraform to test with."
    required: true

  testing_path:
    description: "The path to the directory that contains the Terraform testing configuration."
    required: true

runs:
  using: 'composite'
  defaults:
    run:
      shell: sh
      working-directory: ${{ inputs.testing_path }}

  steps:

    - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.terraform_version }}

      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Initialize the workspace
      - name: Terraform Init
        run: terraform init

      # Apply the Terraform config
      - name: Terraform Apply
        run: terraform apply -auto-approve
