name: 'Terraform Module Testing (Apply Failure)'
description: 'Tests the Terraform module by asserting that an Apply fails with a non-zero exit code.'

inputs:
  tf_path:
    description: "The path to the directory that contains the Terraform configuration."
    required: true

runs:
  using: 'composite'

  steps:

    # Apply the Terraform config without specifying a shell
    - name: Terraform Apply
      if: matrix.shells != 'true'
      id: apply
      continue-on-error: true
      shell: sh
      working-directory: ${{ inputs.tf_path }}
      run: terraform apply -auto-approve
    - name: Check for Failure
      if: matrix.shells != 'true' && steps.apply.outcome != 'failure'
      shell: sh
      run: |
        echo "Apply had a status other than the expected failure: ${{ steps.apply.outcome }}"
        exit 1
